/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorkImport } from './routes/work'
import { Route as ServicesImport } from './routes/services'
import { Route as ReadingImport } from './routes/reading'
import { Route as IndexImport } from './routes/index'
import { Route as BlogIdImport } from './routes/blog/$id'

// Create/Update Routes

const WorkRoute = WorkImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRoute,
} as any)

const ServicesRoute = ServicesImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const ReadingRoute = ReadingImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BlogIdRoute = BlogIdImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/reading': {
      id: '/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof ReadingImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesImport
      parentRoute: typeof rootRoute
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkImport
      parentRoute: typeof rootRoute
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reading': typeof ReadingRoute
  '/services': typeof ServicesRoute
  '/work': typeof WorkRoute
  '/blog/$id': typeof BlogIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reading': typeof ReadingRoute
  '/services': typeof ServicesRoute
  '/work': typeof WorkRoute
  '/blog/$id': typeof BlogIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/reading': typeof ReadingRoute
  '/services': typeof ServicesRoute
  '/work': typeof WorkRoute
  '/blog/$id': typeof BlogIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reading' | '/services' | '/work' | '/blog/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reading' | '/services' | '/work' | '/blog/$id'
  id: '__root__' | '/' | '/reading' | '/services' | '/work' | '/blog/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReadingRoute: typeof ReadingRoute
  ServicesRoute: typeof ServicesRoute
  WorkRoute: typeof WorkRoute
  BlogIdRoute: typeof BlogIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReadingRoute: ReadingRoute,
  ServicesRoute: ServicesRoute,
  WorkRoute: WorkRoute,
  BlogIdRoute: BlogIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/reading",
        "/services",
        "/work",
        "/blog/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/reading": {
      "filePath": "reading.tsx"
    },
    "/services": {
      "filePath": "services.tsx"
    },
    "/work": {
      "filePath": "work.tsx"
    },
    "/blog/$id": {
      "filePath": "blog/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
